### ISSUE TITLE
[Errno 2] No such file or directory: 'captchas/2023-02-02T11-11-51.045534.png'

### ISSUE THREAD

**Issue by Axorimaster** [Ed1123/seace-scraper#1]
Hola! Estoy teniendo el siguiente problema. De acuerdo con la documentación el captcha deberá ser ingresado a mano, pero la opción no aparece al ejecutar el código desde el terminal. [Errno 2] No such file or directory: 'captchas/2023-02-02T11-11-51.045534.png'

**Comment by Ed1123** [comment]
Hola, me parece que el error es porque no tienes una carpeta llamada "captcha". Creo que esa carpeta solo se usaba para debugging, pero no sé llegó a actualizar el código.

**Comment by Axorimaster** [comment]
Muchas gracias Ed! Se pudo sortear el error. Un favor, vi el tema del captch en el cógido. Hay alguna forma de poder quebrarlo? Habí un link a AWS.

Saludos!

**Comment by Ed1123** [comment]
No, lamentablemente no hay forma legal de evitar el captcha.
